'use strict';
window.RECEIPTS_DEMO = {
  profile: { id: 'demo_user', email: 'ben@example.com', name: 'Ben Campbell' },
  clients: [
    { id:'client_brew', name:'Marisol Vega', company:'Barrio Brew Co.', email:'marisol@barriobrew.com', approvalOwner:'Marisol Vega', approvalNote:'Double-check hours, event dates, and beer names.', approvalCode:'482193', roomToken:'demo-barrio-brew', color:'#f95630', colorText:'#fff', initials:'BB', active:true },
    { id:'client_market', name:'Derek Okafor', company:'Southside Night Market', email:'derek@southsidenightmarket.com', approvalOwner:'Derek Okafor', approvalNote:'Vendor count, location, and dates need a final look.', approvalCode:'739421', roomToken:'demo-night-market', color:'#2cc9df', colorText:'#0d0f0c', initials:'NM', active:true },
    { id:'client_salon', name:'Priya Nair', company:'Studio Nair', email:'priya@studionair.co', approvalOwner:'Priya Nair', approvalNote:'Keep captions minimal and polished.', approvalCode:'615804', roomToken:'demo-studio-nair', color:'#bba2ff', colorText:'#0d0f0c', initials:'SN', active:true }
  ],
  posts: [
    { id:'post_1', bufferId:'buf_demo_001', clientId:'client_brew', title:'Fall tap list launch', caption:'Fall is here and so is our new tap list. 🍂 Six new pours, one limited barrel-aged stout, and the return of our fan-favorite horchata cream ale. Come find your new favorite. Open Tue–Sun from 3pm.', image:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80', platform:'Instagram', service:'instagram', status:'approved', bufferStatus:'scheduled', version:3, changedSinceReview:false, approvedBy:'Marisol Vega', approvedAt:'2026-07-10T20:42:00.000Z', receiptCode:'RCP-84N2K7', fingerprint:'7cb61e9b2f4ee2e8a80d', createdAt:'2026-07-01T13:00:00.000Z', comments:[{authorType:'creator',authorName:'Ben',body:'Warm and cozy direction. Let me know on caption length.',kind:'comment',createdAt:'2026-07-10T18:50:00.000Z'},{authorType:'client',authorName:'Marisol',body:'Looks great. Approved for launch.',kind:'approval',createdAt:'2026-07-10T20:42:00.000Z'}] },
    { id:'post_2', bufferId:'buf_demo_002', clientId:'client_brew', title:'Behind the bar reel', caption:'Our head brewer has been working on something special for the past six weeks. Sneak peek dropping Friday.', image:'https://images.unsplash.com/photo-1436076863579-8e5b2f72f5d7?w=900&q=80', platform:'Instagram Reels', service:'instagram', status:'review', bufferStatus:'draft', version:2, changedSinceReview:false, createdAt:'2026-07-08T15:00:00.000Z', comments:[{authorType:'creator',authorName:'Ben',body:'Reel cover is ready. Video is already in Buffer.',kind:'comment',createdAt:'2026-07-10T15:30:00.000Z'}] },
    { id:'post_3', bufferId:'buf_demo_003', clientId:'client_brew', title:'Weekend hours story', caption:'We are open this Saturday 12–10pm for the game. Come early, grab a pint, stay late.', image:'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=900&q=80', platform:'Instagram Story', service:'instagram', status:'changes', bufferStatus:'draft', version:1, changedSinceReview:false, createdAt:'2026-07-09T11:00:00.000Z', feedback:'Hours are wrong—we close at 11pm on Saturdays.', comments:[{authorType:'client',authorName:'Marisol',body:'Hours are wrong—we close at 11pm on Saturdays.',kind:'change',createdAt:'2026-07-10T16:22:00.000Z'}] },
    { id:'post_4', bufferId:'buf_demo_004', clientId:'client_market', title:'October market announcement', caption:'The October Night Market is back. 40+ local vendors, live music, food trucks, and the good people of this city. Oct 19–20 at Hemisfair Park. Free entry.', image:'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=900&q=80', platform:'Instagram', service:'instagram', status:'review', bufferStatus:'needs_approval', version:1, changedSinceReview:true, createdAt:'2026-07-09T10:00:00.000Z', comments:[] },
    { id:'post_5', bufferId:'buf_demo_005', clientId:'client_salon', title:'Rebrand reveal teaser', caption:'Something new is coming to Studio Nair. Stay tuned.', image:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=900&q=80', platform:'Instagram', service:'instagram', status:'draft', bufferStatus:'draft', version:1, changedSinceReview:false, createdAt:'2026-07-10T12:00:00.000Z', comments:[] },
    { id:'post_6', bufferId:'buf_demo_006', clientId:null, title:'Unassigned Buffer draft', caption:'Great content sitting in Buffer, not yet assigned to a client.', image:'', platform:'Threads', service:'threads', status:'draft', bufferStatus:'draft', version:1, changedSinceReview:false, createdAt:'2026-07-10T14:00:00.000Z', comments:[] }
  ],
  receipts: [
    { id:'receipt_1', receiptCode:'RCP-84N2K7', postId:'post_1', clientId:'client_brew', clientCompany:'Barrio Brew Co.', title:'Fall tap list launch', platform:'Instagram', approverName:'Marisol Vega', approvedAt:'2026-07-10T20:42:00.000Z', version:3, fingerprint:'7cb61e9b2f4ee2e8a80d', snapshot:{caption:'Fall is here and so is our new tap list. 🍂 Six new pours, one limited barrel-aged stout, and the return of our fan-favorite horchata cream ale. Come find your new favorite. Open Tue–Sun from 3pm.'} }
  ],
  lastSync: '2026-07-10T20:10:00.000Z'
};
