'use strict';
(function(){
  var U=window.ReceiptsUtil;
  function icon(name,fill){return '<span class="material-symbols-outlined'+(fill?' fill':'')+'">'+name+'</span>';}
  function statusLabel(status){return {draft:'From Buffer',review:'Waiting',changes:'Changes',approved:'Approved'}[status]||status;}
  function platformIcon(platform){var p=String(platform||'').toLowerCase();if(p.includes('instagram'))return 'photo_camera';if(p.includes('linkedin'))return 'work';if(p.includes('threads')||p.includes('twitter')||p.includes('x'))return 'alternate_email';if(p.includes('facebook'))return 'thumb_up';if(p.includes('tiktok'))return 'music_note';return 'public';}
  function badge(status){return '<span class="badge '+U.esc(status)+'">'+U.esc(statusLabel(status))+'</span>';}
  function clientById(data,id){return (data.clients||[]).find(function(c){return c.id===id;});}
  function counts(data){return ['draft','review','changes','approved'].reduce(function(a,s){a[s]=(data.posts||[]).filter(function(p){return p.status===s;}).length;return a;},{});}
  function pageMeta(page){return {board:['Buffer approval board','Board'],clients:['Approval rooms','Clients'],receipts:['The paper trail','Receipts'],settings:['Connection and beta controls','Settings']}[page]||['Receipts','Board'];}
  function navButton(page,current,iconName,label){return '<button class="'+(page===current?'active':'')+'" onclick="ReceiptsActions.go(\''+page+'\')">'+icon(iconName,page===current)+label+'</button>';}
  function shell(state,body){
    var meta=pageMeta(state.page),mode=window.ReceiptsAPI.getMode();
    return '<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">'+icon('receipt_long',true)+'</span><span><strong>Receipts</strong><small>for Buffer users</small></span></div><nav class="side-nav">'
      +navButton('board',state.page,'view_kanban','Board')+navButton('clients',state.page,'group','Clients')+navButton('receipts',state.page,'receipt_long','Receipts')+navButton('settings',state.page,'settings','Settings')
      +'</nav><div class="side-bottom"><div class="mode-card"><b>'+(mode==='demo'?'Interactive demo':'Shared beta')+'</b><small>'+(mode==='demo'?'Supabase is not configured yet. Everything works locally in this browser.':'Supabase persistence and public rooms are active.')+'</small></div><a class="sidebar-link" href="/">← Back to landing page</a></div></aside>'
      +'<main class="workspace"><header class="topbar"><div class="page-title"><small>'+U.esc(meta[0])+'</small><h1>'+U.esc(meta[1])+'</h1></div><div class="top-actions">'+topActions(state.page,state)+'</div></header><section class="content">'+body+'</section></main>'
      +'<nav class="mobile-nav">'+navButton('board',state.page,'view_kanban','Board')+navButton('clients',state.page,'group','Clients')+navButton('receipts',state.page,'receipt_long','Receipts')+navButton('settings',state.page,'settings','Settings')+'</nav></div>';
  }
  function topActions(page,state){
    if(page==='board')return '<button class="btn outline" onclick="ReceiptsActions.sync()">'+icon('sync')+'<span>Sync Buffer</span></button>';
    if(page==='clients')return '<button class="btn primary" onclick="ReceiptsActions.newClient()">'+icon('add')+'<span>New client</span></button>';
    if(page==='receipts')return '<button class="btn outline" onclick="ReceiptsActions.go(\'board\')">'+icon('arrow_back')+'<span>Board</span></button>';
    return '';
  }
  function board(state){
    var data=state.data,c=counts(data);
    var stat='<div class="status-strip">'+[['draft','From Buffer','Ready to assign'],['review','Waiting','With clients'],['changes','Changes','Needs your edit'],['approved','Approved','Receipts created']].map(function(x){return '<div class="stat-card"><span>'+x[1]+'</span><b>'+c[x[0]]+'</b><em>'+x[2]+'</em></div>';}).join('')+'</div>';
    var lanes=[{id:'draft',label:'From Buffer',dot:'#8d9187'},{id:'review',label:'Waiting for approval',dot:'#2cc9df'},{id:'changes',label:'Changes requested',dot:'#f95630'},{id:'approved',label:'Approved',dot:'#92bd00'}];
    var kanban='<div class="kanban">'+lanes.map(function(l){var posts=(data.posts||[]).filter(function(p){return p.status===l.id;});return '<section class="lane"><div class="lane-head"><div><i style="background:'+l.dot+'"></i><b>'+l.label+'</b></div><span>'+posts.length+'</span></div><div class="lane-body">'+(posts.length?posts.map(function(p){return postCard(p,clientById(data,p.clientId));}).join(''):'<div class="empty-lane">Nothing here yet.</div>')+'</div></section>';}).join('')+'</div>';
    return stat+kanban;
  }
  function postCard(p,client){
    var media=p.image?'<img src="'+U.esc(p.image)+'" alt="">':'<div class="post-media placeholder">'+icon(platformIcon(p.platform))+'<span class="post-source">Buffer</span></div>';
    if(p.image)media='<div class="post-media">'+media+'<span class="post-source">Buffer</span></div>';
    return '<article class="post-card" onclick="ReceiptsActions.openPost(\''+U.esc(p.id)+'\')">'+media+'<div class="post-body">'+(p.changedSinceReview?'<div class="changed-flag">'+icon('warning')+'Changed in Buffer—resend required</div>':'')+'<div class="post-top"><div class="post-title">'+U.esc(p.title)+'</div>'+badge(p.status)+'</div><div class="post-caption">'+U.esc(p.caption||'No caption text returned by Buffer.')+'</div><div class="post-meta"><span>'+(client?U.esc(client.company):'Unassigned')+'</span><span>v'+(p.version||1)+'</span></div></div></article>';
  }
  function clients(state){
    var data=state.data;
    if(!(data.clients||[]).length)return '<div class="empty-lane">No client rooms yet. Add the person who gets the final say.</div>';
    return '<div class="grid">'+data.clients.map(function(c){var posts=(data.posts||[]).filter(function(p){return p.clientId===c.id;}),review=posts.filter(function(p){return p.status==='review';}).length,changes=posts.filter(function(p){return p.status==='changes';}).length,approved=posts.filter(function(p){return p.status==='approved';}).length;var room=U.roomUrl(c.roomToken||'');return '<article class="client-card"><div class="client-head"><div class="avatar" style="background:'+U.esc(c.color||'#cafd00')+';color:'+U.esc(c.colorText||'#0d0f0c')+'">'+U.esc(c.initials||U.initials(c.company))+'</div><div><h3>'+U.esc(c.company)+'</h3><p>'+U.esc(c.approvalOwner||c.name)+' · '+U.esc(c.email||'No email')+'</p></div></div><div class="client-stats"><div><b>'+review+'</b><span>Waiting</span></div><div><b>'+changes+'</b><span>Changes</span></div><div><b>'+approved+'</b><span>Approved</span></div></div><div class="owner-kit"><small>Approval room</small><code>'+U.esc(room)+'</code><div class="code-row"><div><small>Owner code</small><b>'+U.esc(c.approvalCode||'Rotate to view')+'</b></div><button class="btn primary" onclick="event.stopPropagation();ReceiptsActions.copyKit(\''+U.esc(c.id)+'\')">Copy kit</button></div></div><div class="tiny-actions"><button class="primary" onclick="ReceiptsActions.copyRoom(\''+U.esc(c.id)+'\')">Copy room</button><button onclick="ReceiptsActions.invite(\''+U.esc(c.id)+'\')">Email invite</button><button onclick="ReceiptsActions.rotate(\''+U.esc(c.id)+'\',\'code\')">Rotate code</button><button onclick="ReceiptsActions.rotate(\''+U.esc(c.id)+'\',\'room\')">Rotate link</button></div></article>';}).join('')+'</div>';
  }
  function receipts(state){var rs=state.data.receipts||[];if(!rs.length)return '<div class="empty-lane">No receipts yet. An approved Buffer snapshot will appear here.</div>';return '<div class="receipt-list">'+rs.map(function(r){return '<article class="receipt-list-card" onclick="ReceiptsActions.openReceipt(\''+U.esc(r.id)+'\')"><div class="receipt-icon">'+icon('verified',true)+'</div><div><h3>'+U.esc(r.title)+'</h3><p>'+U.esc(r.clientCompany)+' · '+U.esc(r.platform)+' · '+U.fmtDateTime(r.approvedAt)+'</p></div><code>'+U.esc(r.receiptCode)+'</code></article>';}).join('')+'</div>';}
  function settings(state){var token=window.ReceiptsAPI.getBufferToken(),remote=window.ReceiptsAPI.getMode()==='remote',data=state.data||{};return '<div class="settings-layout"><article class="settings-card"><h2>Buffer connection</h2><p>For the private beta, users bring their own Buffer token. It stays in this browser and is sent only when you press Sync.</p><div class="notice">The production path is Buffer OAuth. BYO token keeps the first beta smaller while the workflow earns its keep.</div><div class="field"><label>Buffer access token</label><input id="buffer-token" class="input" type="password" value="'+U.esc(token)+'" placeholder="Paste token"></div><div class="tiny-actions"><button class="primary" onclick="ReceiptsActions.saveToken()">Save token</button><button onclick="ReceiptsActions.clearToken()">Clear</button><button onclick="ReceiptsActions.sync()">Test sync</button></div></article><article class="settings-card"><h2>Beta setup</h2><p>The app switches itself into shared mode when the Supabase environment variables are present.</p><div class="setup-list"><div class="setup-item '+(remote?'done':'')+'">'+icon(remote?'check_circle':'radio_button_unchecked',remote)+'<b>Supabase persistence</b></div><div class="setup-item '+(remote?'done':'')+'">'+icon(remote?'check_circle':'radio_button_unchecked',remote)+'<b>Public approval rooms</b></div><div class="setup-item '+(remote?'done':'')+'">'+icon(remote?'check_circle':'radio_button_unchecked',remote)+'<b>Server-side owner codes</b></div><div class="setup-item '+((window.ReceiptsAPI.getConfig().emailConfigured)?'done':'')+'">'+icon(window.ReceiptsAPI.getConfig().emailConfigured?'check_circle':'radio_button_unchecked',window.ReceiptsAPI.getConfig().emailConfigured)+'<b>Resend notifications</b></div></div></article><article class="settings-card"><h2>Current session</h2><p>'+(remote?'Signed in as '+U.esc((data.profile&&data.profile.email)||'beta user'):'Running the local interactive demo. Use Reset to restore the original sample workspace.')+'</p><div class="tiny-actions">'+(remote?'<button onclick="ReceiptsActions.signOut()">Sign out</button>':'<button class="primary" onclick="ReceiptsActions.resetDemo()">Reset demo</button>')+'</div></article><article class="settings-card danger-zone"><h2>V1 boundaries</h2><p>Receipts stores approvals, comments, snapshots, and receipts. Buffer remains the source for creating, hosting, editing, and publishing the post.</p></article></div>';}
  function renderCreator(state){var body=state.page==='clients'?clients(state):state.page==='receipts'?receipts(state):state.page==='settings'?settings(state):board(state);return shell(state,body);}
  function login(){return '<div class="auth-shell"><div class="auth-card"><div class="brand"><span class="brand-mark">'+icon('receipt_long',true)+'</span><span><strong>Receipts</strong><small>for Buffer users</small></span></div><p class="eyebrow">PRIVATE BETA</p><h1>Sign in without another password.</h1><p>Enter your email and Supabase will send a magic link. Clients never need an account.</p><div class="field"><label>Email</label><input id="login-email" class="input" type="email" autocomplete="email" placeholder="you@example.com"></div><button class="btn primary" onclick="ReceiptsActions.login()">'+icon('mail')+'Send magic link</button><p class="auth-note">No Supabase keys configured? The build automatically opens in interactive demo mode.</p></div></div>';}
  function loading(text){return '<div class="loading"><div><div class="spinner"></div>'+U.esc(text||'Loading Receipts…')+'</div></div>';}
  function newClientModal(){var colors=['#cafd00','#f95630','#2cc9df','#bba2ff','#ffcc66'];return '<div class="modal-head"><div><h2>New client room</h2><p>One room, one owner, one private code.</p></div><button class="icon-btn" onclick="ReceiptsUtil.closeModal()">'+icon('close')+'</button></div><div class="modal-body"><div class="field"><label>Company</label><input id="new-company" class="input" placeholder="Barrio Brew Co."></div><div class="field"><label>Approval owner</label><input id="new-owner" class="input" placeholder="Marisol Vega"></div><div class="field"><label>Owner email</label><input id="new-email" class="input" type="email" placeholder="marisol@example.com"></div><div class="field"><label>Review note</label><textarea id="new-note" class="input" placeholder="What should they double-check?"></textarea></div><div class="field"><label>Room color</label><select id="new-color" class="input">'+colors.map(function(c){return '<option value="'+c+'">'+c+'</option>';}).join('')+'</select></div><div class="modal-actions"><button class="btn soft" onclick="ReceiptsUtil.closeModal()">Cancel</button><button class="btn primary" onclick="ReceiptsActions.createClient()">Create room</button></div></div>';}
  function postModal(detail,data){var p=detail.post,c=detail.client,comments=detail.comments||[];return '<div class="modal-head"><div><h2>'+U.esc(p.title)+'</h2><p>Buffer snapshot v'+(p.version||1)+' · '+U.esc(p.platform)+'</p></div><button class="icon-btn" onclick="ReceiptsUtil.closeModal()">'+icon('close')+'</button></div><div class="modal-body"><div class="post-detail-media">'+(p.image?'<img src="'+U.esc(p.image)+'" alt="">':icon(platformIcon(p.platform)))+'</div>'+(p.changedSinceReview?'<div class="notice">This content changed in Buffer after review began. Assign it again only after you are ready to send the latest snapshot.</div>':'')+'<div class="caption-box">'+U.esc(p.caption||'No caption text returned by Buffer.')+'</div><div class="field" style="margin-top:13px"><label>Client room</label><select id="post-client" class="input" onchange="ReceiptsActions.assign(\''+U.esc(p.id)+'\',this.value)"><option value="">Unassigned</option>'+(data.clients||[]).map(function(x){return '<option value="'+U.esc(x.id)+'" '+(x.id===p.clientId?'selected':'')+'>'+U.esc(x.company)+'</option>';}).join('')+'</select></div><div class="tiny-actions">'+(p.clientId&&p.status!=='approved'?'<button class="primary" onclick="ReceiptsActions.sendReview(\''+U.esc(p.id)+'\')">Send latest snapshot</button>':'')+(c?'<button onclick="ReceiptsActions.copyRoom(\''+U.esc(c.id)+'\')">Copy client room</button>':'')+'</div><div class="conversation">'+comments.map(function(x){return '<div class="comment '+(x.authorType==='client'?'client ':'')+(x.kind==='change'?'change':'')+'"><b>'+U.esc(x.authorName)+' · '+U.relative(x.createdAt)+'</b><p>'+U.esc(x.body)+'</p></div>';}).join('')+'</div><div class="field" style="margin-top:13px"><label>Add creator note</label><textarea id="creator-comment" class="input" placeholder="Add context for the client..."></textarea></div><button class="btn soft" onclick="ReceiptsActions.creatorComment(\''+U.esc(p.id)+'\')">Add note</button></div>';}
  function receiptModal(r){var s=r.snapshot||{};return '<div class="modal-head"><div><h2>'+U.esc(r.receiptCode)+'</h2><p>Approved Buffer snapshot</p></div><button class="icon-btn" onclick="ReceiptsUtil.closeModal()">'+icon('close')+'</button></div><div class="modal-body"><div class="approved-stamp">'+icon('verified',true)+'<div><b>Approved by '+U.esc(r.approverName)+'</b><small>'+U.fmtDateTime(r.approvedAt)+'</small></div></div><div class="client-stats"><div><b>'+U.esc(r.clientCompany)+'</b><span>Client</span></div><div><b>'+U.esc(r.platform)+'</b><span>Channel</span></div><div><b>v'+(r.version||1)+'</b><span>Snapshot</span></div></div><div class="caption-box">'+U.esc(s.caption||'')+'</div><div class="field" style="margin-top:13px"><label>Snapshot fingerprint</label><code class="input" style="display:block;word-break:break-all">'+U.esc(r.fingerprint||'')+'</code></div></div>';}
  function reviewRoom(room,token){var c=room.client,posts=room.posts||[],waiting=posts.filter(function(p){return p.status==='review';}).length,changes=posts.filter(function(p){return p.status==='changes';}).length,approved=posts.filter(function(p){return p.status==='approved';}).length;return '<div class="review-shell"><header class="review-header"><div class="brand"><span class="brand-mark">'+icon('receipt_long',true)+'</span><span><strong>Receipts</strong><small>client approval room</small></span></div><div class="client-label"><b>'+U.esc(c.company)+'</b><small>The team comments. The owner stamps.</small></div></header><main class="review-main"><section class="review-intro"><div><p class="eyebrow">CLIENT REVIEW</p><h1>'+U.esc(c.company)+' approval room</h1><p>'+U.esc(c.approvalNote||'Review the active posts below. Anyone can leave feedback; the owner code is required for final approval.')+'</p></div><div class="review-counts"><span>'+waiting+' waiting</span><span>'+changes+' changes</span><span>'+approved+' approved</span></div></section><section class="review-list">'+(posts.length?posts.map(function(p){return reviewCard(p,token,c);}).join(''):'<div class="empty-lane">There are no active posts in this room.</div>')+'</section></main></div>';}
  function reviewCard(p,token,c){var comments=p.comments||[];return '<article class="review-card"><div class="review-card-grid"><div class="review-card-media">'+(p.image?'<img src="'+U.esc(p.image)+'" alt="">':icon(platformIcon(p.platform)))+'</div><div class="review-card-content"><div class="review-card-head"><div><h2>'+U.esc(p.title)+'</h2><div class="platform">'+U.esc(p.platform)+' · Snapshot v'+(p.version||1)+'</div></div>'+badge(p.status)+'</div>'+(p.changedSinceReview?'<div class="notice">This post changed in Buffer. Final approval is locked until the creator resends the latest snapshot.</div>':'')+'<div class="review-caption">'+U.esc(p.caption||'No caption text returned by Buffer.')+'</div><div class="conversation">'+comments.map(function(x){return '<div class="comment '+(x.authorType==='client'?'client ':'')+(x.kind==='change'?'change':'')+'"><b>'+U.esc(x.authorName)+' · '+U.relative(x.createdAt)+'</b><p>'+U.esc(x.body)+'</p></div>';}).join('')+'</div>'+(p.status==='approved'?'<div class="approved-stamp">'+icon('verified',true)+'<div><b>Stamped by '+U.esc(p.approvedBy||c.approvalOwner)+'</b><small>'+U.fmtDateTime(p.approvedAt)+' · '+U.esc(p.receiptCode||'Receipt saved')+'</small></div></div>':'<div class="field" style="margin-top:13px"><label>Your name</label><input id="review-name-'+U.esc(p.id)+'" class="input" value="'+U.esc(c.approvalOwner||'')+'"></div><div class="field"><label>Comment or requested change</label><textarea id="review-body-'+U.esc(p.id)+'" class="input" placeholder="Add specific feedback..."></textarea></div><div class="review-actions"><button class="btn soft" onclick="ReviewActions.comment(\''+U.esc(token)+'\',\''+U.esc(p.id)+'\')">Comment</button><button class="btn danger" onclick="ReviewActions.changes(\''+U.esc(token)+'\',\''+U.esc(p.id)+'\')">Request changes</button><button class="btn primary" '+(p.changedSinceReview||p.status!=='review'?'disabled':'')+' onclick="ReviewActions.approveModal(\''+U.esc(token)+'\',\''+U.esc(p.id)+'\')">'+icon('verified',true)+'Stamp approval</button></div>')+'</div></div></article>';}
  function approveModal(token,postId){var name=document.getElementById('review-name-'+postId);return '<div class="modal-head"><div><h2>Stamp final approval</h2><p>The six-digit code confirms the designated owner has the final say.</p></div><button class="icon-btn" onclick="ReceiptsUtil.closeModal()">'+icon('close')+'</button></div><div class="modal-body"><div class="field"><label>Signing as</label><input id="approval-name" class="input" value="'+U.esc(name?name.value:'')+'"></div><div class="field"><label>Owner code</label><input id="approval-code" class="input" type="password" inputmode="numeric" maxlength="6" placeholder="••••••" style="letter-spacing:.18em;font-weight:900"></div><div class="modal-actions"><button class="btn soft" onclick="ReceiptsUtil.closeModal()">Not yet</button><button class="btn primary" onclick="ReviewActions.approve(\''+U.esc(token)+'\',\''+U.esc(postId)+'\')">Stamp it</button></div></div>';}
  function error(message){return '<div class="error-page"><div>'+icon('link_off')+'<h1>Approval room unavailable</h1><p>'+U.esc(message||'This link may have expired or been rotated.')+'</p></div></div>';}
  window.ReceiptsUI={renderCreator:renderCreator,login:login,loading:loading,newClientModal:newClientModal,postModal:postModal,receiptModal:receiptModal,reviewRoom:reviewRoom,approveModal:approveModal,error:error};
})();
